spring.application.name=customer-service

server.port=8082

spring.profiles.active=dev

spring.config.import=optional:configserver:http://localhost:8888

name=niranj

eureka.instance.hostname=localhost
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8761/eureka/
server.context-path=/customer
