spring.application.name=todel2

server.port=5000

#Facebook OAuth2 configuration
spring.security.oauth2.client.registration.facebook.client-id=1586201238656831
spring.security.oauth2.client.registration.facebook.client-secret=c3afe6d152a27618c14c827a1d72e0be
