server.port=8081
spring.application.name=order-service
spring.profiles.active=dev

# This tells Spring Boot to import config from the Config Server
spring.config.import=optional:configserver:http://localhost:8888
