spring.application.name=oauth2-demo


server.port=5000

spring.security.oauth2.client.registration.facebook.client-id=1586201238656831
spring.security.oauth2.client.registration.facebook.client-secret=c3afe6d152a27618c14c827a1d72e0be

spring.security.oauth2.client.registration.github.client-id=Ov23liIm8q28b7xsl98j
spring.security.oauth2.client.registration.github.client-secret=3e16fe7d1824bba0d33acc69e5dc77e98fb81883
spring.security.oauth2.client.registration.github.scope=read:user,user:email

#Gmail OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=896630674615-tsgcigto95cdj0ca2f2bh15i7e0gsskb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

