spring.application.name=demo-client

server.port=5000

spring.cloud.discovery.client.simple.instances.demo-service[0].uri=http://localhost:8081
spring.cloud.discovery.client.simple.instances.demo-service[1].uri=http://localhost:8082
spring.cloud.discovery.client.simple.instances.demo-service[2].uri=http://localhost:8083


